# Generated by Django 3.0.7 on 2020-06-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melbournehseprice', '0002_auto_20200611_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='datesold',
            field=models.DateField(),
        ),
    ]
