# Generated by Django 3.0.7 on 2020-06-16 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('melbournehseprice', '0003_auto_20200615_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='house',
            new_name='houses',
        ),
    ]
